window.TEMPLATES_DATA = [
    {
        "id": "abilene-downtown-antique-mall-premium-premium",
        "name": "Abilene Downtown Antique Mall",
        "title": "Abilene Downtown Antique Mall (Premium)",
        "tier": "premium",
        "category": "Local Business",
        "status": "In Progress",
        "path": "./Projects/Abilene Downtown Antique Mall/premium/index.html",
        "preview": "./Projects/Abilene Downtown Antique Mall/premium/PreviewImage.bmp",
        "updated": "2026-02-13"
    },
    {
        "id": "counter-strike-premium-premium",
        "name": "Counter Strike",
        "title": "Counter Strike (Premium)",
        "tier": "premium",
        "category": "General Business",
        "status": "In Progress",
        "path": "./Projects/Counter Strike/premium/index.html",
        "preview": "./forgeai-logo.png",
        "updated": "2026-02-13"
    },
    {
        "id": "countrypolitan-business-business",
        "name": "Countrypolitan",
        "title": "Countrypolitan (Business)",
        "tier": "business",
        "category": "General Business",
        "status": "In Progress",
        "path": "./Projects/Countrypolitan/business/index.html",
        "preview": "./Projects/Countrypolitan/business/assets/hero.jpg",
        "updated": "2026-02-13"
    },
    {
        "id": "countrypolitan-starter-starter",
        "name": "Countrypolitan",
        "title": "Countrypolitan (Starter)",
        "tier": "starter",
        "category": "General Business",
        "status": "In Progress",
        "path": "./Projects/Countrypolitan/starter/index.html",
        "preview": "./Projects/Countrypolitan/starter/assets/hero.jpg",
        "updated": "2026-02-13"
    },
    {
        "id": "cypress-bridge-candle-co-premium-premium",
        "name": "Cypress Bridge Candle Co",
        "title": "Cypress Bridge Candle Co (Premium)",
        "tier": "premium",
        "category": "Food & Retail",
        "status": "In Progress",
        "path": "./Projects/Cypress Bridge Candle Co/premium/index.html",
        "preview": "./Projects/Cypress Bridge Candle Co/premium/PreviewImage.bmp",
        "updated": "2026-02-13"
    },
    {
        "id": "cypress-bridge-candle-co-starter-starter",
        "name": "Cypress Bridge Candle Co",
        "title": "Cypress Bridge Candle Co (Starter)",
        "tier": "starter",
        "category": "Food & Retail",
        "status": "In Progress",
        "path": "./Projects/Cypress Bridge Candle Co/starter/index.html",
        "preview": "./Projects/Cypress Bridge Candle Co/premium/assets/logo.png",
        "updated": "2026-02-13"
    },
    {
        "id": "desktopdesignerdashboard-desktopdesignerdashboard-custom",
        "name": "DesktopDesignerDashBoard",
        "title": "DesktopDesignerDashBoard (Custom)",
        "tier": "custom",
        "category": "General Business",
        "status": "In Progress",
        "path": "./Projects/DesktopDesignerDashBoard/index.html",
        "preview": "./Projects/DesktopDesignerDashBoard/Screenshot 2026-02-12 085009.png",
        "updated": "2026-02-13"
    },
    {
        "id": "donutpalace-main-premium-premium",
        "name": "DonutPalace-main",
        "title": "DonutPalace-main (Premium)",
        "tier": "premium",
        "category": "Food & Retail",
        "status": "In Progress",
        "path": "./Projects/DonutPalace-main/index.html",
        "preview": "./Projects/DonutPalace-main/1.webp",
        "updated": "2026-02-13"
    },
    {
        "id": "inventory-management-app-templates-custom",
        "name": "inventory-management-app",
        "title": "inventory-management-app (Custom)",
        "tier": "custom",
        "category": "General Business",
        "status": "In Progress",
        "path": "./Projects/inventory-management-app/templates/index.html",
        "preview": "./Projects/inventory-management-app/PreviewImage.bmp",
        "updated": "2026-02-13"
    },
    {
        "id": "joe-snuffy-s-old-fashioned-grill-business-business",
        "name": "Joe Snuffy_s Old Fashioned Grill",
        "title": "Joe Snuffy_s Old Fashioned Grill (Business)",
        "tier": "business",
        "category": "Food & Retail",
        "status": "In Progress",
        "path": "./Projects/Joe Snuffy_s Old Fashioned Grill/business/index.html",
        "preview": "./Projects/Joe Snuffy_s Old Fashioned Grill/business/assets/images/rustic-diner-interior-01.jpg",
        "updated": "2026-02-13"
    },
    {
        "id": "joe-snuffy-s-old-fashioned-grill-premium-premium",
        "name": "Joe Snuffy_s Old Fashioned Grill",
        "title": "Joe Snuffy_s Old Fashioned Grill (Premium)",
        "tier": "premium",
        "category": "Food & Retail",
        "status": "In Progress",
        "path": "./Projects/Joe Snuffy_s Old Fashioned Grill/premium/index.html",
        "preview": "./Projects/Joe Snuffy_s Old Fashioned Grill/premium/assets/images/high-resolution-cooking-scene-01.jpg",
        "updated": "2026-02-13"
    },
    {
        "id": "material-girls-quilt-shop-premium-premium",
        "name": "Material Girls Quilt Shop",
        "title": "Material Girls Quilt Shop (Premium)",
        "tier": "premium",
        "category": "Local Business",
        "status": "In Progress",
        "path": "./Projects/Material Girls Quilt Shop/index.html",
        "preview": "./Projects/Material Girls Quilt Shop/HeroQuilt.jpg",
        "updated": "2026-02-13"
    },
    {
        "id": "material-girls-quilt-shop-starter-starter",
        "name": "Material Girls Quilt Shop",
        "title": "Material Girls Quilt Shop (Starter)",
        "tier": "starter",
        "category": "Local Business",
        "status": "In Progress",
        "path": "./Projects/Material Girls Quilt Shop/starter/index.html",
        "preview": "./Projects/Material Girls Quilt Shop/starter/media/HeroQuilt.jpg",
        "updated": "2026-02-13"
    },
    {
        "id": "the-cheeze-factory-premium-premium",
        "name": "The Cheeze Factory",
        "title": "The Cheeze Factory (Premium)",
        "tier": "premium",
        "category": "Food & Retail",
        "status": "In Progress",
        "path": "./Projects/The Cheeze Factory/premium/index.html",
        "preview": "./Projects/The Cheeze Factory/premium/CheezeFactoryLogo.png",
        "updated": "2026-02-13"
    },
    {
        "id": "the-flower-box-starter-starter",
        "name": "The Flower Box",
        "title": "The Flower Box (Starter)",
        "tier": "starter",
        "category": "Food & Retail",
        "status": "In Progress",
        "path": "./Projects/The Flower Box/starter/index.html",
        "preview": "./Projects/The Flower Box/Screenshot 2026-02-12 084818.png",
        "updated": "2026-02-13"
    },
    {
        "id": "the-hair-emporium-starter-starter",
        "name": "The Hair Emporium",
        "title": "The Hair Emporium (Starter)",
        "tier": "starter",
        "category": "Local Business",
        "status": "In Progress",
        "path": "./Projects/The Hair Emporium/starter/index.html",
        "preview": "./forgeai-logo.png",
        "updated": "2026-02-13"
    },
    {
        "id": "the-killing-floor-king-premium-premium",
        "name": "The Killing Floor King",
        "title": "The Killing Floor King (Premium)",
        "tier": "premium",
        "category": "Sports & Entertainment",
        "status": "In Progress",
        "path": "./Projects/The Killing Floor King/index.html",
        "preview": "./Projects/The Killing Floor King/assets/gage-1.jpg",
        "updated": "2026-02-13"
    },
    {
        "id": "the-meats-premium-premium",
        "name": "The MEATS",
        "title": "The MEATS (Premium)",
        "tier": "premium",
        "category": "Food & Retail",
        "status": "In Progress",
        "path": "./Projects/The MEATS/premium/index.html",
        "preview": "./Projects/The MEATS/premium/The Meats banner.png",
        "updated": "2026-02-13"
    }
];
